name: Distribute APK to Firebase

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Verify APK exists
      - name: Check APK existence
        run: |
          if [ ! -f ./more/app-release.apk ]; then
            echo "Error: APK no encontrado en ./more/app-release.apk"
            exit 1
          fi

      # Configure Firebase credentials
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-credentials.json

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
        run: |
          firebase appdistribution:distribute ./more/app-release.apk \
            --app "1:410686902807:android:c74035158ef816ac528252" \
            --groups "testers-group" \
            --release-notes "Distribuido automáticamente desde GitHub Actions"
