name: Firebase App Distribution

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download APK artifact
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: android-apk

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Set up Firebase credentials
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json

      # Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app-release.apk \
            --app "1:410686902807:android:c74035158ef816ac528252" \
            --groups "testers-group" \
            --release-notes "Distribuido automáticamente desde GitHub Actions"
