name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x', '18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-node-${{ matrix.node-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Install dependencies
        run: npm install

      # Validación de TypeScript
      - name: TypeScript Check
        run: npm run tsc  # Asegúrate de tener este script en package.json: "tsc": "tsc --noEmit"

      # Ejecutar pruebas unitarias
      - name: Run tests
        run: npm test

      # Guardar resultados de test como artefacto, en caso de fallo
      - name: Upload test results
        if: failure()  # Solo si fallan
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

      - name: Lint code with Expo
        run: expo lint --max-warnings=0

      - name: Build for production
        run: npm run build

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Install dependencies
        run: npm install

      - name: Lint code with ESLint
        run: expo lint --max-warnings=0

      # Validar si hay errores en la compilación de TypeScript
      - name: TypeScript Check
        run: npm run tsc  # Esto asegura que no haya problemas de tipado en el código.

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main'  # Solo se ejecuta si se hace push a la rama main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          ssh usuario@servidor "cd /ruta/proyecto && git pull && npm install && npm run build && pm2 restart app"
