name: CI Pipeline

on:
  # Define cuándo debe ejecutarse
  push:
    branches:
      - develop
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Define el trabajo para la integración continua
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar el entorno (ej. Node.js en este caso)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar pruebas
      - name: Run tests
        run: npm test

      # 5. Analizar estilo del código
      - name: Lint code
        run: npm run lint

      # 6. Opcional: Compilar la aplicación para producción
      - name: Build for production
        run: npm run build
