name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Distribute APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
        run: |
          # Escribe las credenciales en un archivo
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json

          # Verifica si el archivo APK existe
          if [ ! -f app-release.apk ]; then
            echo "Error: APK no encontrado en app-release.apk"
            exit 1
          fi

          # Distribuye el APK
          firebase appdistribution:distribute app-release.apk \
            --app "1:410686902807:android:c74035158ef816ac528252" \
            --groups "testers-group" \
            --release-notes "Distribuido automáticamente desde GitHub Actions"
