name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  distribute-only:
    runs-on: ubuntu-latest
    steps:
      # Checkout el repositorio para acceder al APK
      - name: Checkout code
        uses: actions/checkout@v3

      # Verifica que el APK esté disponible
      - name: Check APK existence
        run: |
          if [ ! -f ./path-to-apk/app-release.apk ]; then
            echo "Error: APK no encontrado en ../../more/app-release.apk"
            exit 1
          fi

      # Instala Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Configura las credenciales de Firebase
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json

      # Sube el APK a Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
        run: |
          firebase appdistribution:distribute ../../more/app-release.apk \
            --app "1:410686902807:android:c74035158ef816ac528252" \
            --groups "testers-group" \
            --release-notes "Distribuido automáticamente desde GitHub Actions"
