name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download APK from direct URL
      - name: Download APK
        run: |
          APK_URL="https://expo.dev/artifacts/eas/wdY1ZbFjJ5QFc5EGTZTQNx.apk"
          echo "Downloading APK from $APK_URL"
          curl -o app-release.apk "$APK_URL"

      # Upload APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app-release.apk

      # Distribute APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
          firebase appdistribution:distribute app-release.apk \
            --app "1:410686902807:android:c74035158ef816ac528252" \
            --groups "testers-group" \
            --release-notes "Distribuido automáticamente desde GitHub Actions"

